### ISSUE TITLE
process data meet error

### ISSUE THREAD

**Issue by Watebear** [SPengLiang/LPCG#1]
hello， i run ‘ python data/kitti/link_kitti_raw.py’，meet error，
Traceback (most recent call last):
  File "data/kitti/link_kitti_raw.py", line 40, in <module>
    os.symlink(img_list[i], os.path.join(image_dst_dir, base_name+'.png'))
FileExistsError: [Errno 17] File exists: './data/kitti/raw_data/2011_09_28/2011_09_28_drive_0001_sync/image_02/data/0000000035.png' -> './data/kitti/kitti_merge/training/image_2/000000.png'

（I did previous step strictly）

**Comment by SPengLiang** [comment]
It seems that the symlink has been created, you can delete these symlinks or this symlink directory and try again.

**Comment by Watebear** [comment]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 106/106 [00:00<00:00, 2607.66it/s]
  0%|                                                                                                                                                                                                   | 0/106 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "data/kitti/link_kitti_raw.py", line 49, in <module>
    with open(calib_cam2cam_path, encoding='utf-8') as fw:
FileNotFoundError: [Errno 2] No such file or directory: './data/kitti/kitti_merge/training/calib_cam2cam/000000.txt'

it still not work

**Comment by Watebear** [comment]
it seems the symbolic is broken

**Comment by Muyiyunzi** [comment]
#2
